<?php


// Firebase API Key
define('FIREBASE_API_KEY', 'AAAAKSsevK8:APA91bGhVMdRr0yJxPIjp00iy0dIHpRLSXOiUENm9VWf9tepKAGZCgZyQOHl1u3DfTDDTb5eKjOaYi4byFylLZN7vqVxsajTTvq2OfjS8kdLMQPW5SqNP7ZLjhLaJFgRBJZUEt3mVxYf');
